behaviour/urls.py
from django.conf.urls import url
from . import views

app_name="behaviour"

urlpatterns = [
    url(r'^(?P<behaviour_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^$', views.index, name='index'),
]

openmis/urls.py
from django.conf.urls import include, url
from django.contrib import admin

# The next two lines are required for import_export
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^student/', include('student.urls')),
    url(r'^behaviour/', include('behaviour.urls')),
    url(r'^staff/', include('staff.urls')),
    url(r'^room/', include('room.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# The + static addition is for Django import_export routines

room/urls.py
from django.conf.urls import url
from . import views

app_name = 'room'

urlpatterns = [
    url(r'^(?P<room_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^$', views.index, name='index'),
]

staff/urls.py
from django.conf.urls import url
from . import views

app_name = "staff"

urlpatterns = [
    # /staff/
    url(r'^(?P<staff_id>[0-9]+)/$', views.detail, name='detail'),
    # /staff/232/
    url(r'^$', views.index, name='index'),
    # /staff/123/update/
    url(r'^(?P<staff_id>[0-9]+)/update/$', views.detail, name='update'),
]

student/urls.py
from django.conf.urls import url
from . import views

app_name = "student"

urlpatterns = [
    # /student/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /student/232/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # /student/123/update/
    url(r'^(?P<pk>[0-9]+)/update/$', views.UpdateView.as_view(), name='update'),
    # /student/add
    url(r'student/add/$', views.StudentCreate.as_view(), name='student-create'),
    # /qualification/
    url(r'qualification/$', views.QualificationIndex.as_view(), name='qualification-index'),
    # /qualification/add
    url(r'qualification/add/$', views.QualificationCreate.as_view(), name='qualification-create'),
]

behaviour/models.py
from django.db import models
from student.models import Student


# Create your models here.
class Behaviour(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    event = models.TextField()

    def __str__(self):
        return self.event

room/models.py
from django.db import models


class Room(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name

staff/models.py
from django.db import models
from django_markdown.models import MarkdownField


class Staff(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    biography = models.TextField()

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

    def test(self):
        return self

student/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Student(models.Model):
    first_name = models.CharField(max_length=50, null=False)
    last_name = models.CharField(max_length=30, null=False)
    gender = models.CharField(max_length=1, null=False)
    date_of_birth = models.DateField(null=True)
    ULN = models.CharField(max_length=10, null=True)

    def get_absolute_url(self):
        return reverse('student:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)


class Qualification(models.Model):
    title = models.CharField(max_length=100, null=False)
    LAR = models.CharField(max_length=12, null=False)

    def get_absolute_url(self):
        return reverse('qualification:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return '%s: %s' % (self.LAR, self.title)

behaviour/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return HttpResponse("<h1>You're at the Behaviour index.</h1>")


def detail(request, behaviour_id):
    response = "<h1>Details for behaviour %s</h1>" %(str(behaviour_id))
    response += "<p>{{}}</p>"
    return HttpResponse(response)

room/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return HttpResponse("<h1>You're at the Room index.</h1>")


def detail(request, room_id):
    return HttpResponse("<h1>Details for room %s</h1>" %(str(room_id)))

staff/views.py
from django.shortcuts import render, get_object_or_404
from .models import Staff


def index(request):
    all_staff = Staff.objects.all()
    return render(request, 'staff/index.html', {'all_staff': all_staff})


def detail(request, staff_id):
    staff = get_object_or_404(Staff, pk=staff_id)
    return render(request, 'staff/detail.html', {'staff': staff})

student/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Student, Qualification


class IndexView(generic.ListView):
    template_name = 'student/index.html'
    context_object_name = 'all_students'

    def get_queryset(self):
        return Student.objects.all()


class DetailView(generic.DetailView):
    model = Student
    template_name = 'student/detail.html'


class UpdateView(generic.UpdateView):
    model = Student
    fields = ['first_name', 'last_name', 'date_of_birth', 'gender', 'ULN']
    template_name = 'student/update.html'


class StudentCreate(CreateView):
    model = Student
    fields = ['first_name', 'last_name', 'date_of_birth', 'gender', 'ULN']


class QualificationIndex(generic.ListView):
    template_name = 'qualification/index.html'
    context_object_name = 'all_qualifications'

    def get_queryset(self):
        return Qualification.objects.all()


class QualificationCreate(CreateView):
    model = Qualification
    fields = ['title', 'LAR']

staff/templates/staff/detail.html
<h3>{{staff}}</h3>
{% if error_message %}
    <p><strong>{{error_message}}</strong></p>
{% endif %}
{{staff.biography}}

staff/templates/staff/index.html
<h1>Staff Index</h1>
{% if all_staff %}
    <ul>
        {% for staff in all_staff %}
        <li>
            <a href="{% url 'staff:detail' staff.id %}">{{staff}}</a>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p>There are no staff records to display.</p>
{% endif %}

student/templates/student/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}OpenCMIS{% endblock %}</title>
    {% load staticfiles %}
    <!-- Link to online resource full of Bootstrap files -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Link to Google online fonts -->
    <link href='https://fonts.googleapis.com/css?family=Righteous' rel='stylesheet' type='text/css'>
    <!-- Link to Google Ajax scripts -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <!-- Link to bootstrap javascript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Basic CSS from tutorial -->
    <link rel="stylesheet" type="text/css" href="{% static 'student/style.css' %}"/>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'student:index' %}">OpenCMIS</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'student:index' %}">
                            <span class="glyphicon glyphicon-education" area-hidden="true"></span>&nbsp;&nbsp;Students
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'behaviour:index' %}">
                            <span class="glyphicon glyphicon-flag" area-hidden="true"></span>&nbsp;&nbsp;Behaviour
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'staff:index' %}">
                            <span class="glyphicon glyphicon-user" area-hidden="true"></span>&nbsp;&nbsp;Staff
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'room:index' %}">
                            <span class="glyphicon glyphicon-bookmark" area-hidden="true"></span>&nbsp;&nbsp;Room
                        </a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-flag" area-hidden="true"></span>&nbsp;&nbsp;Events
                        </a>
                    </li>
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-stats" area-hidden="true"></span>&nbsp;&nbsp;Reports
                        </a>
                    </li>
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-log-out" area-hidden="true"></span>&nbsp;&nbsp;Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block body %}
    {% endblock %}

</body>
</html>

student/templates/student/detail.html
{% extends 'student/base.html' %}
{% block title %}{{student}}{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">Name:</div>
            <div class="col-md-10">{{student}}</div>
        </div>
        <div class="row">
            <div class="col-md-2">Date of Birth:</div>
            <div class="col-md-10">{{student.date_of_birth}}</div>
        </div>
        <div class="row">
            <div class="col-md-2">Gender:</div>
            <div class="col-md-10">{{student.gender}}</div>
        </div>
        <div class="row">
            <div class="col-md-2">ULN:</div>
            <div class="col-md-10">{{student.ULN}}</div>
        </div>
    </div>
{% endblock %}

student/templates/student/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2"></label>
    </div>
{% endfor %}

student/templates/student/index.html
{% extends 'student/base.html' %}
{% block title %}Student Index{% endblock %}
{% block body %}
    <h1>Student Index</h1>
    {% if all_students %}
        <ul>
            {% for student in all_students %}
            <li>
                <a href="{% url 'student:detail' student.id %}">{{student}}</a>
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no student records to display.</p>
    {% endif %}
{% endblock %}

student/templates/student/student_form.html
{% extends 'student/base.html' %}
{% block title %}Add Student{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'student/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

student/templates/student/update-old.html
{% extends 'student/base.html' %}
{% block title %}{{student}}{% endblock %}
{% block body %}
    <h3>{{student}}</h3>
    {% if error_message %}
        <p><strong>{{error_message}}</strong></p>
    {% endif %}
    <form action="{% url 'student:update' student.id %}" method="post">
        {% csrf_token %}
        <label for="first_name{{student.id}}">First name: </label>
        <input type="text" id="first_name{{student.id}}" name="first_name" value="{{student.first_name}}"/>
        <br>
        <label for="last_name{{student.id}}">Last name: </label>
        <input type="text" id="last_name{{student.id}}" name="last_name" value="{{student.last_name}}"/>
        <br>
        <input type="submit" value="Save"/>
        <input type="reset" value="Cancel"/>
    </form>
{% endblock %}

student/templates/student/update.html
{% extends 'student/base.html' %}
{% block title %}{{student}}{% endblock %}
{% block body %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
{% endblock %}